# Generated by Django 5.2 on 2025-04-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispensa',
            old_name='nim',
            new_name='militar',
        ),
    ]
