# Generated by Django 5.2 on 2025-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracao_log_servico_militar_escalas_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='feriados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de datas dos feriados no formato YYYY-MM-DD'),
        ),
    ]
