# Generated by Django 5.2 on 2025-04-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_escala_sequencia_fds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='militares',
        ),
    ]
