# Generated by Django 5.2 on 2025-04-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('posto', models.CharField(max_length=50)),
                ('funcao', models.CharField(max_length=50)),
                ('ordem_semana', models.IntegerField()),
                ('ordem_fds', models.IntegerField()),
                ('telefone', models.BigIntegerField()),
                ('e_administrador', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Dispensa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motivo', models.TextField()),
                ('nim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensas', to='core.militar')),
            ],
        ),
    ]
