# Generated by Django 5.2 on 2025-04-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='posto',
            field=models.CharField(choices=[('OF', 'Oficiais'), ('CF', 'Coronel'), ('TC', 'Tenente-Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('TEN', 'Tenente'), ('AL', 'Alferes'), ('S', 'Sargentos'), ('SM', 'Sargento-Mor'), ('SAJ', 'Sargento-Ajudante'), ('S1', 'Primeiro-Sargento'), ('S2', 'Segundo-Sargento'), ('PRA', 'Praças'), ('FUR', 'Furriel'), ('1CAB', 'Primeiro-Cabo'), ('CAB', 'Cabo'), ('ANS', 'Anspeçada'), ('SOL', 'Soldado')], max_length=30),
        ),
    ]
