# Generated by Django 5.2 on 2025-04-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_militar_posto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AddField(
            model_name='configuracao',
            name='inicio_semana',
            field=models.CharField(choices=[('DS', 'Durante a Semana'), ('FS', 'Fim de Semana')], default='DS', help_text='Define se a semana começa durante a semana (DS) ou no fim de semana (FS)', max_length=2),
        ),
    ]
