# Generated by Django 5.2 on 2025-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_configuracao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='inicio_semana',
            field=models.CharField(choices=[('SEG', 'Segunda-feira'), ('DOM', 'Domingo')], default='SEG', help_text='Define se a semana começa na Segunda-feira ou no Domingo', max_length=3),
        ),
    ]
