# Generated by Django 5.2 on 2025-04-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuracao_inicio_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='usar_feriados_nacionais',
            field=models.BooleanField(default=True, help_text='Se marcado, inclui automaticamente os feriados nacionais portugueses'),
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('FIXO', 'Feriado Fixo'), ('MOVEL', 'Feriado Móvel')], default='FIXO', max_length=5)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados_personalizados', to='core.configuracao')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data'],
            },
        ),
    ]
