# Generated by Django 5.2 on 2025-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_militar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='sequencia_fds',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='sequencia_semana',
        ),
        migrations.RemoveField(
            model_name='militar',
            name='escalas',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='lista_militares',
        ),
        migrations.AddField(
            model_name='escala',
            name='militares',
            field=models.ManyToManyField(blank=True, related_name='escalas', to='core.militar'),
        ),
        migrations.AddField(
            model_name='servico',
            name='militares',
            field=models.ManyToManyField(blank=True, related_name='servicos', to='core.militar'),
        ),
    ]
