# Generated by Django 5.2 on 2025-04-13 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracao_usar_feriados_nacionais_feriado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='feriados',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='n_dias',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='n_elementos',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='tem_escala_B',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='armamento_necessario',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='local',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='n_elementos_dia',
        ),
        migrations.AddField(
            model_name='servico',
            name='armamento',
            field=models.BooleanField(default=False, help_text='Se o serviço requer armamento'),
        ),
        migrations.AddField(
            model_name='servico',
            name='hora_fim',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Hora de fim do serviço'),
        ),
        migrations.AddField(
            model_name='servico',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Hora de início do serviço'),
        ),
        migrations.AddField(
            model_name='servico',
            name='n_elementos',
            field=models.IntegerField(default=1, help_text='Número de elementos necessários por escala'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='militares',
            field=models.ManyToManyField(related_name='servicos', to='core.militar'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tem_escala_B',
            field=models.BooleanField(default=False, help_text='Se o serviço tem escala B'),
        ),
    ]
