# Generated by Django 5.2 on 2025-04-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_configuracao_feriados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='configuracao',
        ),
    ]
