# Generated by Django 5.2 on 2025-04-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_configuracao_usar_feriados_nacionais_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'ordering': ['data', 'servico'], 'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        migrations.AddField(
            model_name='escala',
            name='falta',
            field=models.BooleanField(default=False, verbose_name='Falta'),
        ),
        migrations.AddField(
            model_name='escala',
            name='militar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas_atribuidas', to='core.militar'),
        ),
        migrations.AddField(
            model_name='escala',
            name='militar_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_reserva', to='core.militar'),
        ),
        migrations.AddField(
            model_name='escala',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='escala',
            name='prevista',
            field=models.BooleanField(default=True, verbose_name='Prevista'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='e_escala_b',
            field=models.BooleanField(default=False, verbose_name='Escala B'),
        ),
    ]
