# Generated by Django 5.2 on 2025-04-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_militar_posto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='falta',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='prevista',
        ),
    ]
