# Generated by Django 5.2 on 2025-04-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_escala_falta_remove_escala_prevista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='militar',
            options={'verbose_name': 'Militar', 'verbose_name_plural': 'Militares'},
        ),
        migrations.RemoveField(
            model_name='escala',
            name='militar',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='militar_reserva',
        ),
    ]
