# Generated by Django 5.2 on 2025-04-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_militar_options_remove_escala_militar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militar',
            name='ordem_fds',
        ),
        migrations.RemoveField(
            model_name='militar',
            name='ordem_semana',
        ),
    ]
