# Generated by Django 5.2 on 2025-04-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_militar_ordem_fds_remove_militar_ordem_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaMilitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_semana', models.IntegerField(blank=True, null=True)),
                ('ordem_fds', models.IntegerField(blank=True, null=True)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='militares_info', to='core.escala')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.militar')),
            ],
            options={
                'unique_together': {('escala', 'militar')},
            },
        ),
    ]
