# Generated by Django 5.2 on 2025-04-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_escalamilitar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalamilitar',
            options={'verbose_name': 'Militares Na Escala', 'verbose_name_plural': 'Militares Na Escala'},
        ),
    ]
