# Generated by Django 5.2 on 2025-04-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_escala_prevista_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraNomeacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_folga', models.CharField(choices=[('mesma_escala', 'Mesma Escala (A/B)'), ('entre_escalas', 'Entre Escalas (A/B)')], max_length=20)),
                ('horas_minimas', models.IntegerField(help_text='Número mínimo de horas de folga')),
                ('prioridade_modernos', models.BooleanField(default=True, help_text='Prioridade para militares mais modernos')),
                ('considerar_ultimo_servico', models.BooleanField(default=True, help_text='Considerar data do último serviço')),
                ('permitir_trocas', models.BooleanField(default=True, help_text='Permitir trocas de serviço')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_nomeacao', to='core.servico')),
            ],
            options={
                'verbose_name': 'Regra de Nomeação',
                'verbose_name_plural': 'Regras de Nomeação',
                'unique_together': {('servico', 'tipo_folga')},
            },
        ),
    ]
