# Generated by Django 5.2 on 2025-04-16 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_regranomeacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'ordering': ['data'], 'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('servico', 'data', 'e_escala_b')},
        ),
        migrations.AddField(
            model_name='militar',
            name='ultimo_servico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='militar',
            name='nim',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='militar',
            name='posto',
            field=models.CharField(choices=[('COR', 'Coronel'), ('TCOR', 'Tenente-Coronel'), ('MAJ', 'Major'), ('CAP', 'Capitão'), ('TEN', 'Tenente'), ('ALF', 'Alferes'), ('ASP', 'Aspirante'), ('SCH', 'Sargento-Chefe'), ('SAJ', 'Sargento-Ajudante'), ('1SARG', 'Primeiro-Sargento'), ('2SARG', 'Segundo-Sargento'), ('FUR', 'Furriel'), ('2FUR', '2ºFurriel'), ('CABSEC', 'Cabo de Secção'), ('CADJ', 'Cabo-Ajunto'), ('1CAB', 'Primeiro-Cabo'), ('2CAB', 'Segundo-Cabo'), ('SOL', 'Soldado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='militar',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servico',
            name='armamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servico',
            name='hora_fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='servico',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='n_elementos',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tem_escala_B',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='escala',
            name='comentario',
        ),
        migrations.CreateModel(
            name='Nomeacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('posicao', models.CharField(choices=[('efetivo', 'Efetivo'), ('reserva', 'Reserva')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomeacoes', to='core.escala')),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomeacoes', to='core.militar')),
            ],
            options={
                'ordering': ['data', 'posicao'],
                'unique_together': {('militar', 'data')},
            },
        ),
    ]
