# Generated by Django 5.2 on 2025-04-16 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_update_militar_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militar',
            name='ultimo_servico',
        ),
        migrations.AddField(
            model_name='militar',
            name='ultima_nomeacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultima_nomeacao_militar', to='core.nomeacao'),
        ),
    ]
