# Generated by Django 5.2 on 2025-04-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_update_militar_ultima_nomeacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalamilitar',
            options={'ordering': ['ordem'], 'verbose_name': 'Militares Na Escala', 'verbose_name_plural': 'Militares Na Escala'},
        ),
        migrations.RenameField(
            model_name='escalamilitar',
            old_name='ordem_fds',
            new_name='ordem',
        ),
        migrations.RemoveField(
            model_name='escalamilitar',
            name='ordem_semana',
        ),
    ]
