# Generated by Django 5.2 on 2025-04-22 08:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_escalamilitar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militar',
            name='ultima_nomeacao',
        ),
        migrations.AlterModelOptions(
            name='escala',
            options={'ordering': ['data', 'servico'], 'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        migrations.AlterModelOptions(
            name='escalamilitar',
            options={'verbose_name': 'Militares Na Escala', 'verbose_name_plural': 'Militares Na Escala'},
        ),
        migrations.RenameField(
            model_name='escalamilitar',
            old_name='ordem',
            new_name='ordem_fds',
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='escala',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escalamilitar',
            name='ordem_semana',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='militar',
            name='nim',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='militar',
            name='posto',
            field=models.CharField(choices=[('COR', 'Coronel'), ('TCOR', 'Tenente-Coronel'), ('MAJ', 'Major'), ('CAP', 'Capitão'), ('TEN', 'Tenente'), ('ALF', 'Alferes'), ('ASP', 'Aspirante'), ('SCH', 'Sargento-Chefe'), ('SAJ', 'Sargento-Ajudante'), ('1SARG', 'Primeiro-Sargento'), ('2SARG', 'Segundo-Sargento'), ('FUR', 'Furriel'), ('2FUR', '2ºFurriel'), ('CABSEC', 'Cabo de Secção'), ('CADJ', 'Cabo-Ajunto'), ('1CAB', 'Primeiro-Cabo'), ('2CAB', 'Segundo-Cabo'), ('SOL', 'Soldado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='militar',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servico',
            name='armamento',
            field=models.BooleanField(default=False, help_text='Se o serviço requer armamento'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='hora_fim',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Hora de fim do serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Hora de início do serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servico',
            name='n_elementos',
            field=models.IntegerField(default=1, help_text='Número de elementos necessários por escala'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tem_escala_B',
            field=models.BooleanField(default=False, help_text='Se o serviço tem escala B'),
        ),
        migrations.DeleteModel(
            name='Nomeacao',
        ),
    ]
