# Generated by Django 5.2 on 2025-04-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_militar_ultima_nomeacao_alter_escala_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='prevista',
            field=models.BooleanField(default=True, verbose_name='Prevista'),
        ),
    ]
