# Generated by Django 5.2 on 2025-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_escala_prevista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='prevista',
        ),
        migrations.AddField(
            model_name='escala',
            name='nomeacao_prevista',
            field=models.BooleanField(default=True, verbose_name='Nomeação Prevista'),
        ),
    ]
