# Generated by Django 5.2 on 2025-04-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_prevista_to_nomeacao_prevista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalamilitar',
            options={'ordering': ['ordem_semana', 'ordem_fds'], 'verbose_name': 'Nomeação', 'verbose_name_plural': 'Nomeações'},
        ),
        migrations.AlterUniqueTogether(
            name='escalamilitar',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='escala',
            name='nomeacao_prevista',
        ),
        migrations.AddField(
            model_name='escalamilitar',
            name='posicao',
            field=models.CharField(choices=[('efetivo', 'Efetivo'), ('reserva', 'Reserva')], default='efetivo', max_length=10),
        ),
        migrations.AlterField(
            model_name='escalamilitar',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escala'),
        ),
    ]
