# Generated by Django 5.2 on 2025-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_escalamilitar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='prevista',
            field=models.BooleanField(default=False, verbose_name='Prevista'),
        ),
    ]
