# Generated by Django 5.2 on 2025-04-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_escala_prevista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalamilitar',
            options={'verbose_name': 'Militares Na Escala', 'verbose_name_plural': 'Militares Na Escala'},
        ),
        migrations.AlterModelOptions(
            name='previsaoescalasproxy',
            options={'verbose_name': 'Previsões de Nomeação', 'verbose_name_plural': 'Previsões de Nomeação'},
        ),
        migrations.AlterUniqueTogether(
            name='escalamilitar',
            unique_together={('escala', 'militar')},
        ),
        migrations.AlterField(
            model_name='escalamilitar',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='militares_info', to='core.escala'),
        ),
        migrations.RemoveField(
            model_name='escalamilitar',
            name='posicao',
        ),
    ]
