# Generated by Django 5.2 on 2025-04-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_escalamilitar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='prevista',
        ),
    ]
