# Generated by Django 5.2 on 2025-04-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_escala_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='prevista',
            field=models.BooleanField(default=True, verbose_name='Prevista'),
        ),
    ]
