# Generated by Django 5.2 on 2025-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_escala_prevista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='tem_escala_B',
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_escalas',
            field=models.CharField(choices=[('A', 'Só Escala A'), ('B', 'Só Escala B'), ('AB', 'Escala A e B')], default='A', help_text='Que escalas existem neste serviço', max_length=2),
        ),
    ]
