# Generated by Django 5.2 on 2025-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_escala_prevista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalamilitar',
            options={'ordering': ['militar__posto', '-militar__nim'], 'verbose_name': 'Militares Na Escala', 'verbose_name_plural': 'Militares Na Escala'},
        ),
        migrations.AddField(
            model_name='escalamilitar',
            name='e_reserva',
            field=models.BooleanField(default=False, verbose_name='É Reserva'),
        ),
    ]
