# Generated by Django 5.2 on 2025-04-25 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_escalamilitar_options_escalamilitar_e_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalamilitar',
            options={'ordering': ['data', 'militar__posto', '-militar__nim'], 'verbose_name': 'Militares Na Escala', 'verbose_name_plural': 'Militares Na Escala'},
        ),
        migrations.AlterUniqueTogether(
            name='escalamilitar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='escalamilitar',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='escalamilitar',
            unique_together={('escala', 'militar', 'data')},
        ),
    ]
