# Generated by Django 5.2 on 2025-04-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_servico_tem_escala_b_servico_tipo_escalas'),
        ('core', '0035_alter_escalamilitar_options_and_more'),
    ]

    operations = [
    ]
