# Generated by Django 5.2 on 2025-04-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_merge_20250429_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalamilitar',
            options={'verbose_name': 'Militares Na Escala', 'verbose_name_plural': 'Militares Na Escala'},
        ),
        migrations.AlterUniqueTogether(
            name='escalamilitar',
            unique_together={('escala', 'militar')},
        ),
        migrations.RemoveField(
            model_name='escalamilitar',
            name='data',
        ),
        migrations.RemoveField(
            model_name='escalamilitar',
            name='e_reserva',
        ),
    ]
