# Generated by Django 5.2 on 2025-04-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_escalamilitar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalamilitar',
            name='e_reserva',
            field=models.BooleanField(default=False, verbose_name='É Reserva'),
        ),
    ]
