# Generated by Django 5.2 on 2025-04-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_escalamilitar_e_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ordem_entrada_fds',
            field=models.JSONField(default=list, help_text='Lista ordenada de IDs dos militares para fins de semana e feriados'),
        ),
        migrations.AddField(
            model_name='servico',
            name='ordem_entrada_semana',
            field=models.JSONField(default=list, help_text='Lista ordenada de IDs dos militares para dias úteis'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo_escalas',
            field=models.CharField(choices=[('A', 'Só Escala A'), ('B', 'Só Escala B'), ('AB', 'Escala A e B')], default='A', help_text='Que tipo de escalas compõem este serviço.', max_length=2),
        ),
    ]
