# Generated by Django 5.2 on 2025-05-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_servico_ordem_entrada_fds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEscalasProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Histórico de Nomeações',
                'verbose_name_plural': 'Histórico de Nomeações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.escala',),
        ),
        migrations.RemoveField(
            model_name='servico',
            name='ordem_entrada_fds',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='ordem_entrada_semana',
        ),
        migrations.AddField(
            model_name='servico',
            name='n_reservas',
            field=models.IntegerField(default=1, help_text='Número de elementos reserva necessários por escala'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='n_elementos',
            field=models.IntegerField(default=1, help_text='Número de elementos efetivos necessários por escala'),
        ),
    ]
