# Generated by Django 5.2 on 2025-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_historicoescalasproxy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'ordering': ['servico'], 'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        # migrations.AlterUniqueTogether(
        #     name='escalamilitar',
        #     unique_together=set(),
        # ),
        migrations.RemoveField(
            model_name='escala',
            name='data',
        ),
        migrations.AddField(
            model_name='escalamilitar',
            name='data',
            field=models.DateField(default='2025-05-01'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='escalamilitar',
            unique_together={('militar', 'data')},
        ),
    ]
