# Generated by Django 5.2 on 2025-05-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_escala_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='escalamilitar',
            unique_together={('escala', 'militar'), ('militar', 'data')},
        ),
    ]
