# Generated by Django 5.2 on 2025-05-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_escalamilitar_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalamilitar',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
